/**
 * wrap.js — Post-build: copies dist/index.html → gas/Index.html
 * Run: node scripts/wrap.js   (or via npm run wrap)
 */
import { readFileSync, writeFileSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const src  = resolve(root, 'dist', 'index.html')
const dest = resolve(root, 'gas', 'Index.html')

if (!existsSync(src)) {
  console.error('❌  dist/index.html not found. Run `npm run build` first.')
  process.exit(1)
}

const html   = readFileSync(src, 'utf8')
const banner = `<!-- Built: ${new Date().toISOString()} — DO NOT EDIT, regenerated by scripts/wrap.js -->\n`
writeFileSync(dest, banner + html, 'utf8')
console.log(`✅  gas/Index.html updated  (${(html.length / 1024).toFixed(1)} KB)`)
